/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import { Swiper, SwiperSlide } from 'swiper/react';

import 'swiper/css';

import GitCard from '../components/GitCard';
import QualificationCard from '../components/QualificationCard';

import LanguagesBox from '../components/LanguagesBox'
import styles from '../styles/Home.module.css'

export default function Home({ userInfos, repoInfos, languages }) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
        <nav className={styles.navbar}>
          <div className={styles.navbararea}>
            <div className='nav-items'>
              <a href='#Home_inicio__Rib5P' className={styles.naviten} id={styles.active}>
                <img className={styles.navicon} src='https://api-requests.000webhostapp.com/svg/home-svg.svg' alt='' width="20"/>
              </a>
              <a href='#Home_sobre__3C2xF' className={styles.naviten}>
                <img className={styles.navicon} src='https://api-requests.000webhostapp.com/svg/person-svg.svg' alt='' width="20"/>
              </a>
              <a href='#inicio' className={styles.naviten}>
                <img className={styles.navicon} src='https://api-requests.000webhostapp.com/svg/file-svg.svg' alt='' width="20"/>
              </a>
              <a href='#inicio' className={styles.naviten}>
                <img className={styles.navicon} src='https://api-requests.000webhostapp.com/svg/email-svg.svg' alt='' width="20"/>
              </a>
            </div>
          </div>
        </nav>

        <section id={styles.inicio}>
          <div className={styles.inicioarea}>
            <div className={styles.inicioinfoarea}>
                <div className={styles.myinfos}>
                    <h1 className={styles.userName}>{userInfos.name}</h1>
                    <p className={styles.serviceName}>{userInfos.service}</p>
                </div>
                <div className={styles.socialarea}>
                </div>
            </div>
            <div className={styles.inicioinfoarea}>
              <div>
                <LanguagesBox array={languages} className={styles.qualiBox}/>
              </div>
            </div>
          </div>
          <div className={styles.iniciofooter}>
            <img className={styles.wave} src='https://api-requests.000webhostapp.com/svg/wave-top.svg' alt=''/>
            <img className={styles.arrowDown} src='https://api-requests.000webhostapp.com/svg/arrow-svg.svg' alt='' width={30}/>
          </div>
        </section>
        
        <section id={styles.sobre}>
          <div className={styles.infosuser}>

          </div>
          <Swiper
            spaceBetween={50}
            slidesPerView={4}
            navigation={true}
            pagination={{ clickable: true }}
            scrollbar={{ draggable: true }}
            className={styles.gitAreaSwiper}
            breakpoints={{
              450: {
                slidesPerView: 1,
              },
              620: {
                slidesPerView: 2,
              },
              750: {
                slidesPerView: 4,
              },
            }}
          >
          {languages.map((item, key) => (
            <SwiperSlide key={key}>
              <QualificationCard data={item} />
            </SwiperSlide>
          ))}
          </Swiper>
        </section>

        <section id={styles.progetos}>
          <div className={styles.gitArea}>
            {repoInfos.map((item, key) => <GitCard key={key} data={item} />)}
          </div>
        </section>
      </main>
    </div>
  )
}

export const getServerSideProps = async () => {
  const urlI = process.env.APICONECTION_URI;

  const data = await fetch(`${urlI}/api/portfolio`);
  const dataInfo = await data.json();

  return {
    props: {
      userInfos: dataInfo.userInfos,
      repoInfos: dataInfo.repoInfos,
      languages: dataInfo.languages
    }
  }
}