/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'

import styles from '../styles/Home.module.css'

export default function Home({ userInfos }) {
  const src = userInfos.photo;

  const mainHost = 'https://api-requests.000webhostapp.com'
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
        <nav className={styles.navbar}>
          <div className={styles.navbararea}>
            <div className='nav-items'>
              <a href='#inicio' className={styles.naviten} id={styles.active}>
              </a>
              <a href='#sobre' className={styles.naviten}>
              </a>
              <a href='#inicio' className={styles.naviten}>
              </a>
              <a href='#inicio' className={styles.naviten}>
              </a>
            </div>
          </div>
        </nav>

        <section id={styles.inicio}>
          <div className={styles.inicioarea}>
            <div className={styles.inicioinfoarea}>
                <div className={styles.myinfos}>
                    <h1 className={styles.userName}>{userInfos.name}</h1>
                    <p className={styles.serviceName}>{userInfos.service}</p>
                </div>
                <div className={styles.socialarea}>
                </div>
            </div>
          </div>
        </section>
        
        <section id={styles.sobre}>
        </section>
      </main>
    </div>
  )
}

export const getStaticProps = async () => {
  const res = await fetch('https://portfolio-cadu-api.herokuapp.com/users/1');
  const userInfos = await res.json();

  return {
    props: {
      userInfos
    }
  }
}